### ISSUE TITLE
when enabling astral starmetal armor it adds the crafting recipe but not the armor

### ISSUE THREAD

**Issue by spyguy26** [ArcAios26/astraladditions#1]
MOD VERSIONS:
astralsorcery-1.12.2-1.10.27
astraladditions-1.12.2-1.0.0
SCREENSHOTS:
![2021-06-04_01 13 42](https://user-images.githubusercontent.com/39753561/120749316-63b64d00-c4d2-11eb-8599-fa6020f5cc4c.png)
![2021-06-04_01 13 49](https://user-images.githubusercontent.com/39753561/120749317-63b64d00-c4d2-11eb-90cb-29c4b0c7a4a2.png)
![2021-06-04_01 13 52](https://user-images.githubusercontent.com/39753561/120749318-644ee380-c4d2-11eb-97ea-6e06ad0b28c1.png)

**Comment by ArcAios26** [comment]
fixed in commit #e5e156ba051257777943246a79efcb36ca81d705. updated release soon on curseforge.
