### ISSUE TITLE
Crashing on Server

### ISSUE THREAD

**Issue by criscky** [ArcAios26/astraladditions#2]
crash report
https://paste.gg/p/anonymous/131f4c7b856148b6a7ebd6b10b016c51/files/f5174b6ee9c34ea986a3cae9ce8cfb7c/raw

log
https://paste.gg/p/anonymous/a4e47982f6ce46389a6ae55acf8c0543/files/97970dbeb802414db83b399ab2b3d80e/raw

**Comment by ArcAios26** [comment]
Fixed in commit #71e2d1d1bb52cbfc22f3f164d8ec0eaf3f30fc63. Updated release will be uploaded to curseforge soon.
